# Generated by Django 4.1.5 on 2023-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
