# Generated by Django 4.1.5 on 2023-01-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_filiere_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matiere',
            new_name='Cours',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_matiere',
            new_name='identifiant',
        ),
        migrations.AddField(
            model_name='creneau',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.cours'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='filiere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.filiere'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.prof'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.salle'),
        ),
    ]
