# Generated by Django 4.1.5 on 2023-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_matiere_cours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cour'},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Département'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'Filière'},
        ),
        migrations.AlterModelOptions(
            name='prof',
            options={'verbose_name': 'Professeur'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Promotion'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'verbose_name': 'Salle'},
        ),
        migrations.AddField(
            model_name='salle',
            name='nom',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
