# Generated by Django 4.1.5 on 2023-01-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_cours_options_alter_dept_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='prenom',
        ),
    ]
